package main

import (
	"bufio"
	"crypto/rand"
	"database/sql"
	"encoding/hex"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	_ "github.com/lib/pq"
	"github.com/spf13/cobra"
)

const (
	devUserID = "00000000-0000-0000-0000-000000000001"
	devTeamID = "00000000-0000-0000-0000-000000000002"

	localEnvPath = ".fleetlift/local.env" //nolint:unused
	authJSONPath = ".fleetlift/auth.json" //nolint:unused

	sourceLineMarker = "[ -f ~/.fleetlift/local.env ] && source ~/.fleetlift/local.env"
)

type localEnvConfig struct {
	DatabaseURL             string
	TemporalAddress         string
	TemporalUIURL           string
	OpenSandboxDomain       string
	OpenSandboxAPIKey       string
	AgentImage              string
	GitUserEmail            string
	GitUserName             string
	JWTSecret               string
	CredentialEncryptionKey string
	DevNoAuth               bool
	DevUserID               string
	DevTeamID               string
	// Exactly one of these is set:
	AnthropicAPIKey  string
	ClaudeOAuthToken string
	// Optional:
	GitHubToken string
}

func generateHexSecret(n int) string {
	b := make([]byte, n)
	if _, err := rand.Read(b); err != nil {
		panic(err)
	}
	return hex.EncodeToString(b)
}

func writeLocalEnv(path string, cfg localEnvConfig) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		return err
	}

	var sb strings.Builder
	sb.WriteString("# Fleetlift local dev environment — generated by 'fleetlift init-local'\n")
	sb.WriteString("# Source this file or let scripts/integration/dev-env.sh load it automatically.\n\n")

	line := func(k, v string) {
		fmt.Fprintf(&sb, "export %s=%q\n", k, v)
	}

	line("DATABASE_URL", cfg.DatabaseURL)
	line("TEMPORAL_ADDRESS", cfg.TemporalAddress)
	line("TEMPORAL_UI_URL", cfg.TemporalUIURL)
	line("OPENSANDBOX_DOMAIN", cfg.OpenSandboxDomain)
	line("OPENSANDBOX_API_KEY", cfg.OpenSandboxAPIKey)
	line("AGENT_IMAGE", cfg.AgentImage)
	line("GIT_USER_EMAIL", cfg.GitUserEmail)
	line("GIT_USER_NAME", cfg.GitUserName)
	sb.WriteString("\n# Auth\n")
	line("JWT_SECRET", cfg.JWTSecret)
	line("CREDENTIAL_ENCRYPTION_KEY", cfg.CredentialEncryptionKey)
	sb.WriteString("\n# Dev auth bypass\n")
	if cfg.DevNoAuth {
		sb.WriteString("export DEV_NO_AUTH=1\n")
	}
	line("DEV_USER_ID", cfg.DevUserID)
	line("DEV_TEAM_ID", cfg.DevTeamID)
	sb.WriteString("\n# Claude agent auth\n")
	if cfg.AnthropicAPIKey != "" {
		line("ANTHROPIC_API_KEY", cfg.AnthropicAPIKey)
	} else if cfg.ClaudeOAuthToken != "" {
		line("CLAUDE_CODE_OAUTH_TOKEN", cfg.ClaudeOAuthToken)
	}
	if cfg.GitHubToken != "" {
		sb.WriteString("\n# GitHub\n")
		line("GITHUB_TOKEN", cfg.GitHubToken)
	}

	return os.WriteFile(path, []byte(sb.String()), 0o600)
}

func patchDevEnv(scriptPath string) error {
	data, err := os.ReadFile(scriptPath)
	if err != nil {
		return err
	}
	content := string(data)

	// Idempotency check
	if strings.Contains(content, sourceLineMarker) {
		return nil
	}

	scanner := bufio.NewScanner(strings.NewReader(content))
	var lines []string
	for scanner.Scan() {
		lines = append(lines, scanner.Text())
	}
	if len(lines) == 0 {
		return nil
	}

	// Insert after shebang (line 0)
	patched := make([]string, 0, len(lines)+1)
	patched = append(patched, lines[0])
	patched = append(patched, sourceLineMarker)
	patched = append(patched, lines[1:]...)

	return os.WriteFile(scriptPath, []byte(strings.Join(patched, "\n")+"\n"), 0o755)
}

func seedDevIdentity(dbURL string) error {
	db, err := sql.Open("postgres", dbURL)
	if err != nil {
		return fmt.Errorf("open db: %w", err)
	}
	defer db.Close()

	// Wait for Postgres to be ready
	deadline := time.Now().Add(30 * time.Second)
	for {
		if err := db.Ping(); err == nil {
			break
		}
		if time.Now().After(deadline) {
			return fmt.Errorf("postgres not ready after 30s — run 'docker compose up -d' and try again")
		}
		time.Sleep(1 * time.Second)
		fmt.Print(".")
	}
	fmt.Println()

	_, err = db.Exec(`INSERT INTO teams (id, name, slug) VALUES ($1, 'dev-team', 'dev-team') ON CONFLICT (slug) DO NOTHING`, devTeamID)
	if err != nil {
		return fmt.Errorf("upsert team: %w", err)
	}

	_, err = db.Exec(`INSERT INTO users (id, name, provider, provider_id) VALUES ($1, 'Dev User', 'dev', $1) ON CONFLICT (provider, provider_id) DO NOTHING`, devUserID)
	if err != nil {
		return fmt.Errorf("upsert user: %w", err)
	}

	_, err = db.Exec(`INSERT INTO team_members (team_id, user_id, role) VALUES ($1, $2, 'admin') ON CONFLICT (team_id, user_id) DO NOTHING`, devTeamID, devUserID)
	if err != nil {
		return fmt.Errorf("upsert team_members: %w", err)
	}

	return nil
}

func initLocalCmd() *cobra.Command {
	return &cobra.Command{
		Use:   "init-local",
		Short: "Interactive wizard to set up a local development environment",
		RunE:  runInitLocal,
	}
}

func runInitLocal(_ *cobra.Command, _ []string) error {
	// Implemented in Task 4
	return fmt.Errorf("not yet implemented")
}
