package main

import (
	"bufio"
	"crypto/rand"
	"database/sql"
	"encoding/hex"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"

	"github.com/charmbracelet/huh"
	_ "github.com/lib/pq"
	"github.com/spf13/cobra"
)

const (
	devUserID = "00000000-0000-0000-0000-000000000001"
	devTeamID = "00000000-0000-0000-0000-000000000002"

	localEnvPath = ".fleetlift/local.env" //nolint:unused
	authJSONPath = ".fleetlift/auth.json" //nolint:unused

	sourceLineMarker = "[ -f ~/.fleetlift/local.env ] && source ~/.fleetlift/local.env"
)

type localEnvConfig struct {
	DatabaseURL             string
	TemporalAddress         string
	TemporalUIURL           string
	OpenSandboxDomain       string
	OpenSandboxAPIKey       string
	AgentImage              string
	GitUserEmail            string
	GitUserName             string
	JWTSecret               string
	CredentialEncryptionKey string
	DevNoAuth               bool
	DevUserID               string
	DevTeamID               string
	// Exactly one of these is set:
	AnthropicAPIKey  string
	ClaudeOAuthToken string
	// Optional:
	GitHubToken string
}

func generateHexSecret(n int) string {
	b := make([]byte, n)
	if _, err := rand.Read(b); err != nil {
		panic(err)
	}
	return hex.EncodeToString(b)
}

func writeLocalEnv(path string, cfg localEnvConfig) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		return err
	}

	var sb strings.Builder
	sb.WriteString("# Fleetlift local dev environment — generated by 'fleetlift init-local'\n")
	sb.WriteString("# Source this file or let scripts/integration/dev-env.sh load it automatically.\n\n")

	line := func(k, v string) {
		fmt.Fprintf(&sb, "export %s=%q\n", k, v)
	}

	line("DATABASE_URL", cfg.DatabaseURL)
	line("TEMPORAL_ADDRESS", cfg.TemporalAddress)
	line("TEMPORAL_UI_URL", cfg.TemporalUIURL)
	line("OPENSANDBOX_DOMAIN", cfg.OpenSandboxDomain)
	line("OPENSANDBOX_API_KEY", cfg.OpenSandboxAPIKey)
	line("AGENT_IMAGE", cfg.AgentImage)
	line("GIT_USER_EMAIL", cfg.GitUserEmail)
	line("GIT_USER_NAME", cfg.GitUserName)
	sb.WriteString("\n# Auth\n")
	line("JWT_SECRET", cfg.JWTSecret)
	line("CREDENTIAL_ENCRYPTION_KEY", cfg.CredentialEncryptionKey)
	sb.WriteString("\n# Dev auth bypass\n")
	if cfg.DevNoAuth {
		sb.WriteString("export DEV_NO_AUTH=1\n")
	}
	line("DEV_USER_ID", cfg.DevUserID)
	line("DEV_TEAM_ID", cfg.DevTeamID)
	sb.WriteString("\n# Claude agent auth\n")
	if cfg.AnthropicAPIKey != "" {
		line("ANTHROPIC_API_KEY", cfg.AnthropicAPIKey)
	} else if cfg.ClaudeOAuthToken != "" {
		line("CLAUDE_CODE_OAUTH_TOKEN", cfg.ClaudeOAuthToken)
	}
	if cfg.GitHubToken != "" {
		sb.WriteString("\n# GitHub\n")
		line("GITHUB_TOKEN", cfg.GitHubToken)
	}

	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, []byte(sb.String()), 0o600); err != nil {
		return err
	}
	return os.Rename(tmp, path)
}

func patchDevEnv(scriptPath string) error {
	info, err := os.Stat(scriptPath)
	if err != nil {
		return err
	}

	data, err := os.ReadFile(scriptPath)
	if err != nil {
		return err
	}
	content := string(data)

	// Idempotency check
	if strings.Contains(content, sourceLineMarker) {
		return nil
	}

	scanner := bufio.NewScanner(strings.NewReader(content))
	var lines []string
	for scanner.Scan() {
		lines = append(lines, scanner.Text())
	}
	if len(lines) == 0 {
		return fmt.Errorf("patchDevEnv: %s is empty or unreadable", scriptPath)
	}
	if !strings.HasPrefix(lines[0], "#!") {
		return fmt.Errorf("patchDevEnv: %s does not start with a shebang line", scriptPath)
	}

	// Insert after shebang (line 0)
	patched := make([]string, 0, len(lines)+1)
	patched = append(patched, lines[0])
	patched = append(patched, sourceLineMarker)
	patched = append(patched, lines[1:]...)

	return os.WriteFile(scriptPath, []byte(strings.Join(patched, "\n")+"\n"), info.Mode())
}

// adminDSN is the superuser DSN matching the docker-compose postgres service.
const adminDSN = "postgres://temporal:temporal@localhost:5432/postgres?sslmode=disable"

// ensureFleetliftDB creates the fleetlift role and database if they don't exist.
// Connects as the temporal superuser which is created by docker-compose.
func ensureFleetliftDB() error {
	db, err := sql.Open("postgres", adminDSN)
	if err != nil {
		return fmt.Errorf("open admin db: %w", err)
	}
	defer db.Close()

	// Wait for Postgres to be ready
	deadline := time.Now().Add(30 * time.Second)
	for {
		if err := db.Ping(); err == nil {
			break
		}
		if time.Now().After(deadline) {
			return fmt.Errorf("postgres not ready after 30s — run 'docker compose up -d' and try again")
		}
		time.Sleep(1 * time.Second)
		fmt.Print(".")
		os.Stdout.Sync() //nolint:errcheck
	}
	fmt.Println()

	// Create role if not exists
	_, err = db.Exec(`DO $$ BEGIN
		IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'fleetlift') THEN
			CREATE USER fleetlift WITH PASSWORD 'fleetlift';
		END IF;
	END $$`)
	if err != nil {
		return fmt.Errorf("create role: %w", err)
	}

	// Create database if not exists (CREATE DATABASE cannot run in a transaction)
	var exists bool
	if err := db.QueryRow(`SELECT EXISTS(SELECT 1 FROM pg_database WHERE datname = 'fleetlift')`).Scan(&exists); err != nil {
		return fmt.Errorf("check database: %w", err)
	}
	if !exists {
		if _, err := db.Exec(`CREATE DATABASE fleetlift OWNER fleetlift`); err != nil {
			return fmt.Errorf("create database: %w", err)
		}
	}

	return nil
}

// applySchema runs the embedded schema.sql against the fleetlift database.
// schema.sql uses CREATE TABLE IF NOT EXISTS so this is safe to run repeatedly.
func applySchema(appDSN string) error {
	schema, err := os.ReadFile("internal/db/schema.sql")
	if err != nil {
		return fmt.Errorf("read schema.sql: %w", err)
	}
	db, err := sql.Open("postgres", appDSN)
	if err != nil {
		return fmt.Errorf("open db: %w", err)
	}
	defer db.Close()
	if _, err := db.Exec(string(schema)); err != nil {
		return fmt.Errorf("apply schema: %w", err)
	}
	return nil
}

func seedDevIdentity(dbURL string) error {
	db, err := sql.Open("postgres", dbURL)
	if err != nil {
		return fmt.Errorf("open db: %w", err)
	}
	defer db.Close()

	_, err = db.Exec(`INSERT INTO teams (id, name, slug) VALUES ($1, 'dev-team', 'dev-team') ON CONFLICT (slug) DO NOTHING`, devTeamID)
	if err != nil {
		return fmt.Errorf("upsert team: %w", err)
	}

	_, err = db.Exec(`INSERT INTO users (id, name, provider, provider_id) VALUES ($1, 'Dev User', 'dev', $1) ON CONFLICT (provider, provider_id) DO NOTHING`, devUserID)
	if err != nil {
		return fmt.Errorf("upsert user: %w", err)
	}

	_, err = db.Exec(`INSERT INTO team_members (team_id, user_id, role) VALUES ($1, $2, 'admin') ON CONFLICT (team_id, user_id) DO NOTHING`, devTeamID, devUserID)
	if err != nil {
		return fmt.Errorf("upsert team_members: %w", err)
	}

	return nil
}

func initLocalCmd() *cobra.Command {
	return &cobra.Command{
		Use:   "init-local",
		Short: "Interactive wizard to set up a local development environment",
		RunE:  runInitLocal,
	}
}

func runInitLocal(_ *cobra.Command, _ []string) error {
	fmt.Println("╔══════════════════════════════════════╗")
	fmt.Println("║   Fleetlift — Local Setup Wizard     ║")
	fmt.Println("╚══════════════════════════════════════╝")
	fmt.Println()

	// Step 1: Preflight — Docker running?
	if err := exec.Command("docker", "info").Run(); err != nil {
		return fmt.Errorf("Docker is not running. Start Docker Desktop and try again")
	}

	// Step 2 + 3: Collect secrets from user
	var (
		claudeAuthMethod string // "api_key" or "oauth_token"
		anthropicKey     string
		oauthToken       string
		githubToken      string
	)

	authForm := huh.NewForm(
		huh.NewGroup(
			huh.NewSelect[string]().
				Title("Claude authentication method").
				Options(
					huh.NewOption("Anthropic API key (ANTHROPIC_API_KEY)", "api_key"),
					huh.NewOption("Claude OAuth token (CLAUDE_CODE_OAUTH_TOKEN)", "oauth_token"),
				).
				Value(&claudeAuthMethod),
		),
	)
	if err := authForm.Run(); err != nil {
		return err
	}

	var secretForm *huh.Form
	if claudeAuthMethod == "api_key" {
		secretForm = huh.NewForm(
			huh.NewGroup(
				huh.NewInput().
					Title("Anthropic API key").
					Description("Starts with sk-ant-api").
					EchoMode(huh.EchoModePassword).
					Value(&anthropicKey).
					Validate(func(s string) error {
						if strings.TrimSpace(s) == "" {
							return fmt.Errorf("required")
						}
						return nil
					}),
				huh.NewInput().
					Title("GitHub personal access token (optional)").
					Description("Required for workflows that interact with GitHub repos. Press Enter to skip.").
					EchoMode(huh.EchoModePassword).
					Value(&githubToken),
			),
		)
	} else {
		secretForm = huh.NewForm(
			huh.NewGroup(
				huh.NewInput().
					Title("Claude OAuth token").
					Description("Starts with sk-ant-oat01-").
					EchoMode(huh.EchoModePassword).
					Value(&oauthToken).
					Validate(func(s string) error {
						if strings.TrimSpace(s) == "" {
							return fmt.Errorf("required")
						}
						return nil
					}),
				huh.NewInput().
					Title("GitHub personal access token (optional)").
					Description("Required for workflows that interact with GitHub repos. Press Enter to skip.").
					EchoMode(huh.EchoModePassword).
					Value(&githubToken),
			),
		)
	}
	if err := secretForm.Run(); err != nil {
		return err
	}

	// Step 4: Generate secrets
	cfg := localEnvConfig{
		DatabaseURL:             "postgres://fleetlift:fleetlift@localhost:5432/fleetlift?sslmode=disable",
		TemporalAddress:         "localhost:7233",
		TemporalUIURL:           "http://localhost:8233",
		OpenSandboxDomain:       "http://localhost:8090",
		OpenSandboxAPIKey:       "",
		AgentImage:              "claude-code-sandbox:latest",
		GitUserEmail:            "claude-agent@noreply.localhost",
		GitUserName:             "Claude Code Agent",
		JWTSecret:               generateHexSecret(32),
		CredentialEncryptionKey: generateHexSecret(32),
		DevNoAuth:               true,
		DevUserID:               devUserID,
		DevTeamID:               devTeamID,
		AnthropicAPIKey:         strings.TrimSpace(anthropicKey),
		ClaudeOAuthToken:        strings.TrimSpace(oauthToken),
		GitHubToken:             strings.TrimSpace(githubToken),
	}

	// Step 5: Write ~/.fleetlift/local.env
	home, err := os.UserHomeDir()
	if err != nil {
		return err
	}
	envPath := filepath.Join(home, localEnvPath)

	if _, statErr := os.Stat(envPath); statErr == nil {
		var overwrite bool
		overwriteForm := huh.NewForm(
			huh.NewGroup(
				huh.NewConfirm().
					Title(envPath + " already exists. Overwrite?").
					Value(&overwrite),
			),
		)
		if err := overwriteForm.Run(); err != nil {
			return err
		}
		if !overwrite {
			fmt.Println("Skipping env file write. Using existing local.env.")
		} else {
			if err := writeLocalEnv(envPath, cfg); err != nil {
				return fmt.Errorf("write local.env: %w", err)
			}
			fmt.Println("✓ Written:", envPath)
		}
	} else {
		if err := writeLocalEnv(envPath, cfg); err != nil {
			return fmt.Errorf("write local.env: %w", err)
		}
		fmt.Println("✓ Written:", envPath)
	}

	// Step 6: Patch dev-env.sh
	devEnvScript := "scripts/integration/dev-env.sh"
	if err := patchDevEnv(devEnvScript); err != nil {
		fmt.Printf("Warning: could not patch %s: %v\n", devEnvScript, err)
		fmt.Printf("Manually add this line after the shebang in %s:\n  %s\n", devEnvScript, sourceLineMarker)
	} else {
		fmt.Println("✓ Patched:", devEnvScript)
	}

	// Step 7: Start Docker stacks
	var startDocker bool
	dockerForm := huh.NewForm(
		huh.NewGroup(
			huh.NewConfirm().
				Title("Start Docker Compose stacks now? (Temporal + Postgres + OpenSandbox)").
				Value(&startDocker),
		),
	)
	if err := dockerForm.Run(); err != nil {
		return err
	}

	if startDocker {
		fmt.Println("Starting Temporal + Postgres...")
		if err := execCmd("docker", "compose", "up", "-d"); err != nil {
			return fmt.Errorf("docker compose up failed: %w", err)
		}
		fmt.Println("Starting OpenSandbox...")
		if err := execCmd("docker", "compose", "-f", "docker-compose.opensandbox.yaml", "up", "-d"); err != nil {
			return fmt.Errorf("docker compose opensandbox up failed: %w", err)
		}
	} else {
		var alreadyUp bool
		alreadyUpForm := huh.NewForm(
			huh.NewGroup(
				huh.NewConfirm().
					Title("Are the Docker stacks already running? Proceed with database setup?").
					Value(&alreadyUp),
			),
		)
		if err := alreadyUpForm.Run(); err != nil {
			return err
		}
		if !alreadyUp {
			printManualSteps()
			return nil
		}
	}

	// Step 8: Create DB, apply schema, seed dev identity
	fmt.Print("Waiting for Postgres")
	if err := ensureFleetliftDB(); err != nil {
		return fmt.Errorf("setup database: %w", err)
	}
	fmt.Println("✓ Database ready")
	if err := applySchema(cfg.DatabaseURL); err != nil {
		return fmt.Errorf("apply schema: %w", err)
	}
	fmt.Println("✓ Schema applied")
	if err := seedDevIdentity(cfg.DatabaseURL); err != nil {
		return fmt.Errorf("seed dev identity: %w", err)
	}
	fmt.Println("✓ Dev identity seeded (team + user + membership)")

	// Write ~/.fleetlift/auth.json
	// "dev-token" is a placeholder — the server ignores the token value when DEV_NO_AUTH=1.
	// The devAuthBypass middleware skips JWT validation and injects claims from DEV_USER_ID/DEV_TEAM_ID env vars.
	if err := saveToken("dev-token"); err != nil {
		return fmt.Errorf("write auth.json: %w", err)
	}
	fmt.Println("✓ Written:", filepath.Join(home, authJSONPath))

	// Step 9: Print next steps
	fmt.Println()
	fmt.Println("┌─────────────────────────────────────────┐")
	fmt.Println("│   Local environment ready!              │")
	fmt.Println("└─────────────────────────────────────────┘")
	fmt.Println()
	fmt.Println("Start the server and worker:")
	fmt.Println("  scripts/integration/start.sh")
	fmt.Println()
	fmt.Println("Tail logs:")
	fmt.Println("  scripts/integration/logs.sh")
	fmt.Println()
	fmt.Println("Temporal UI: http://localhost:8233")
	fmt.Println("Fleetlift:   http://localhost:8080")
	return nil
}

func execCmd(name string, args ...string) error {
	c := exec.Command(name, args...)
	c.Stdout = os.Stdout
	c.Stderr = os.Stderr
	return c.Run()
}

func printManualSteps() {
	fmt.Println()
	fmt.Println("Start the stacks manually, then re-run 'fleetlift init-local':")
	fmt.Println()
	fmt.Println("  docker compose up -d")
	fmt.Println("  docker compose -f docker-compose.opensandbox.yaml up -d")
}
